# Generated by Django 3.2.13 on 2023-07-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7, null=True, verbose_name='Номер дня (дней)')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Описание дня')),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Описание изображения')),
                ('icon', models.ImageField(null=True, upload_to='photos/icons', verbose_name='Изображение дня')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя, Фамилия')),
                ('review', models.TextField(max_length=1000, null=True, verbose_name='Содержание отзыва')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Название на английском')),
                ('title1', models.CharField(max_length=50, null=True, verbose_name='Название 1 строка')),
                ('title2', models.CharField(max_length=50, null=True, verbose_name='Название 2 строка')),
                ('dateStart', models.DateField(null=True, verbose_name='Дата начала тура')),
                ('dateEnd', models.DateField(null=True, verbose_name='Дата окончания тура')),
                ('tagline', models.CharField(max_length=50, verbose_name='Слоган для 2 секции')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание для 2 секции')),
                ('image1Section2', models.ImageField(upload_to='photos/', verbose_name='Изображение 1 для 2 секции')),
                ('image2Section2', models.ImageField(upload_to='photos/', verbose_name='Изображение 2 для 2 секции')),
                ('image3Section2', models.ImageField(upload_to='photos/', verbose_name='Изображение 3 для 2 секции')),
                ('priceAdult', models.CharField(blank=True, max_length=15, null=True, verbose_name='Цена для взрослых')),
                ('priceChild', models.CharField(blank=True, max_length=15, null=True, verbose_name='Цена для взрослых')),
                ('isActive', models.BooleanField(default=True, null=True, verbose_name='Действующий тур')),
                ('isOutside', models.BooleanField(default=True, null=True, verbose_name='Тур с выездом на зраницу')),
                ('isOneDay', models.BooleanField(default=False, null=True, verbose_name='Поездка выходного дня')),
                ('backgroundSection1', models.ImageField(null=True, upload_to='photos/', verbose_name='Фон первой секции')),
                ('backgroundAdditionalServices', models.ImageField(null=True, upload_to='photos/', verbose_name='Фон секции дополнительных услуг')),
                ('backgroundSectionBooking', models.ImageField(null=True, upload_to='photos/', verbose_name='Фон секции забронировать')),
            ],
        ),
        migrations.CreateModel(
            name='NotInclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Что включено в стоимость')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Подробное описание')),
                ('price', models.CharField(blank=True, max_length=15, null=True, verbose_name='Цена дополнительной услуги')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.icon', verbose_name='Иконка')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.tour', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Что включено в стоимость')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Подробное описание')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.icon', verbose_name='Иконка')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.tour', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='ImageForDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Описание изображения')),
                ('image', models.ImageField(null=True, upload_to='photos/days', verbose_name='Изображение дня')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.day', verbose_name='День')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.tour', verbose_name='Тур'),
        ),
    ]
