# Generated by Django 3.2.13 on 2023-07-22 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_icon_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.functions.comparison.Coalesce('dateStart', datetime.date(9999, 12, 31))]},
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageforday',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='tour.day', verbose_name='День'),
        ),
    ]
