# Generated by Django 3.2.13 on 2023-07-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20230722_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.tour', verbose_name='Тур'),
        ),
    ]
