# Generated by Django 3.2.13 on 2023-07-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_review_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.tour', verbose_name='Поездка, о которой хотите оставить отзыв'),
        ),
    ]
