# Generated by Django 3.2.13 on 2023-07-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_review_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyWe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Почему мы')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Подробно, почему мы')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.icon', verbose_name='Иконка')),
            ],
        ),
    ]
