# Generated by Django 3.2.13 on 2023-08-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_whywe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name="Ім'я, Прізвище")),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Електронна пошта')),
                ('permitToEmail', models.BooleanField(default=True, verbose_name='Я хочу отримувати на електронну пошту щодо майбутніх поїздок')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name="Ім'я, Прізвище"),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=1000, null=True, verbose_name='Зміст відгуку'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.tour', verbose_name='Поїздка, про яку ви хочете залишити відгук'),
        ),
    ]
