# Generated by Django 3.2.13 on 2023-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20230802_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефону'),
        ),
    ]
