# Generated by Django 3.2.13 on 2023-08-06 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_alter_client_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2023, 8, 6), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='day',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Опис дня'),
        ),
        migrations.AlterField(
            model_name='day',
            name='number',
            field=models.CharField(max_length=7, null=True, verbose_name='Номер дня (днів)'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.FileField(null=True, upload_to='photos/icons', verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Опис зображення'),
        ),
        migrations.AlterField(
            model_name='imageforday',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/days', verbose_name='Зображення дня'),
        ),
        migrations.AlterField(
            model_name='imageforday',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Опис зображення'),
        ),
        migrations.AlterField(
            model_name='inclusive',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Подробний опис'),
        ),
        migrations.AlterField(
            model_name='inclusive',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.icon', verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='inclusive',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Що включено у вартість'),
        ),
        migrations.AlterField(
            model_name='notinclusive',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Подробний опис'),
        ),
        migrations.AlterField(
            model_name='notinclusive',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.icon', verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='notinclusive',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна додаткової послуги'),
        ),
        migrations.AlterField(
            model_name='notinclusive',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Що входить у вартість'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='backgroundAdditionalServices',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Фон секції додаткових послуг'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='backgroundSection1',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Фон першої секції'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='backgroundSectionBooking',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Фон секції забронювати'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='dateEnd',
            field=models.DateField(null=True, verbose_name='Дата закінчення туру'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='dateStart',
            field=models.DateField(null=True, verbose_name='Дата початку туру'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Опис для 2 секції'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image1Section2',
            field=models.ImageField(upload_to='photos/', verbose_name='Зображення 1 для 2 секції'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image2Section2',
            field=models.ImageField(upload_to='photos/', verbose_name='Зображення 2 для 2 секції'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image3Section2',
            field=models.ImageField(upload_to='photos/', verbose_name='Зображення 3 для 2 секції'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='isActive',
            field=models.BooleanField(default=True, null=True, verbose_name='Діючий тур'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='isOneDay',
            field=models.BooleanField(default=False, null=True, verbose_name='Поїздка вихідного дня'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='isOutside',
            field=models.BooleanField(default=True, null=True, verbose_name='Закордонний тур'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='priceAdult',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна для дорослих'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='priceChild',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна для дітей'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tagline',
            field=models.CharField(max_length=50, verbose_name='Слоган для 2 секції'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Назва англійською'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title1',
            field=models.CharField(max_length=50, null=True, verbose_name='Назва 1 строка'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title2',
            field=models.CharField(max_length=50, null=True, verbose_name='Назва 2 строка'),
        ),
        migrations.AlterField(
            model_name='whywe',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Подробно, чому ми'),
        ),
        migrations.AlterField(
            model_name='whywe',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.icon', verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='whywe',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Чому ми'),
        ),
        migrations.CreateModel(
            name='ImageForGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='photos/days', verbose_name='Зображення дня')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='tour.tour', verbose_name='Тур')),
            ],
        ),
    ]
