# Generated by Django 3.2.13 on 2023-08-16 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_auto_20230806_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2023, 8, 16), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AlterField(
            model_name='day',
            name='description',
            field=models.TextField(max_length=1500, null=True, verbose_name='Опис дня'),
        ),
        migrations.AlterField(
            model_name='day',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tour.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='imageforday',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.day', verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='imageforgalery',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/galery', verbose_name='Зображення дня'),
        ),
        migrations.AlterField(
            model_name='imageforgalery',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='inclusive',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.icon', verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='inclusive',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='notinclusive',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.icon', verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='notinclusive',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='Поїздка, про яку ви хочете залишити відгук'),
        ),
        migrations.AlterField(
            model_name='whywe',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.icon', verbose_name='Іконка'),
        ),
    ]
