# Generated by Django 3.2.13 on 2023-09-01 12:56

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_auto_20230816_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(dateStart=None, then=django.db.models.expressions.Value(1)), django.db.models.expressions.When(dateStart__lt=datetime.date(2023, 9, 1), then=django.db.models.expressions.Value(2)), default=django.db.models.expressions.Value(0), output_field=models.IntegerField()), 'dateStart']},
        ),
        migrations.AddField(
            model_name='tour',
            name='dateBeforeAdult',
            field=models.DateField(blank=True, null=True, verbose_name='Дата, до якої діє скидка дорослим'),
        ),
        migrations.AddField(
            model_name='tour',
            name='dateBeforeChild',
            field=models.DateField(blank=True, null=True, verbose_name='Дата, до якої діє скидка дітям'),
        ),
        migrations.AddField(
            model_name='tour',
            name='priceAdultBefore',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна для дорослих зі скидкою'),
        ),
        migrations.AddField(
            model_name='tour',
            name='priceChildBefore',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ціна для дітей зі скидкою'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='dateEnd',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закінчення туру'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tagline',
            field=models.CharField(max_length=55, verbose_name='Слоган для 2 секції'),
        ),
    ]
